language: go
go:
  - 1.8
install:
  - go get github.com/apex/log
	- go get github.com/spf13/viper
	- go get github.com/spf13/cobra
  - go get -v .
  - go get github.com/golang/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...
